#!/bin/sh
DEFAULT_DEV_USER="postgres"
DEFAULT_DEV_PASSWORD="postgres"
DEFAULT_DEV_DB_NAME="tso_greenhouses"

psql -c "CREATE ROLE $DEFAULT_DEV_USER WITH PASSWORD '$DEFAULT_DEV_PASSWORD' LOGIN SUPERUSER"
psql -c "CREATE DATABASE $DEFAULT_DEV_DB_NAME"
psql -c "ALTER DATABASE $DEFAULT_DEV_DB_NAME OWNER TO $DEFAULT_DEV_USER"
