version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - .postgres/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local